'use strict';
/* OmniTradeX // bounded research and coaching ledger */
(function () {
  var KEY = 'otx_coaching_ledger_v1';
  var ledger = []; try { ledger = JSON.parse(localStorage.getItem(KEY)) || []; } catch (e) { ledger = []; }
  function save() { localStorage.setItem(KEY, JSON.stringify(ledger.slice(-100))); }
  function snapshot() { var s = state.active, d = state.last[s] || {}; var b = state.buffers[s] || []; var mean = b.reduce(function (a, x) { return a + x; }, 0) / (b.length || 1); var drift = mean ? ((d.price - mean) / mean) * 100 : 0; return { symbol: s, price: d.price, delta: d.delta, driftFromMean: Number(drift.toFixed(3)), source: state.marketMode || 'UNKNOWN', strategy: window.activeStrategyName || 'ICT Liquidity Recon', journalCount: window.journal ? window.journal.length : 0 }; }
  function render(result) { var box = document.getElementById('coaching-output'); if (!box) return; box.replaceChildren(); Object.keys(result).forEach(function (k) { var p = document.createElement('p'); p.className = 'flex justify-between gap-3 border-b border-gridline/60 py-1.5'; var a = document.createElement('span'); a.className = 'text-slate-500 uppercase'; a.textContent = k.replace(/([A-Z])/g, ' $1'); var b = document.createElement('span'); b.className = 'text-slate-200 text-right'; b.textContent = String(result[k]); p.append(a, b); box.appendChild(p); }); }
  function coach() { var s = snapshot(); var regime = Math.abs(s.driftFromMean) > 0.35 ? 'MOMENTUM / EXTENDED' : 'BALANCED / WAIT'; var setup = s.source === 'LIVE' ? (regime === 'BALANCED / WAIT' ? 'No validated edge; wait for structure.' : 'Observe continuation only after confirmation.') : 'Live feed required before research signal.'; var result = { regime: regime, setup: setup, invalidation: 'A close back through the short-term mean invalidates the observation.', risks: 'Exchange latency, spread, slippage, news shock; educational output only.', confidence: s.source === 'LIVE' ? '54%' : '0%', evidence: s.symbol + ' // delta ' + Number(s.delta || 0).toFixed(2) + '% // mean drift ' + s.driftFromMean + '%', lesson: 'Separate observation from execution. Record the reason before acting.', questions: 'What would prove this thesis wrong? What is the maximum acceptable risk?' }; ledger.push({ at: Date.now(), snapshot: s, result: result }); save(); render(result); var st = document.getElementById('coach-status'); if (st) st.textContent = 'COACHING // UPDATED ' + new Date().toLocaleTimeString(); }
  var btn = document.getElementById('btn-coach'); if (btn) btn.addEventListener('click', coach); window.otxAgent = { coach: coach, ledger: ledger, snapshot: snapshot };
}());
